const KEY="lhwm_v2";
const cfg=window.SUPABASE_CONFIG||{};
const sb=(window.supabase&&cfg.url&&cfg.anonKey)?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const seed={tasks:[{id:1,title:"Tuyển 30 lao động đơn hàng Trung Quốc",dept:"Cung ứng lao động",assignee:"Nguyễn Văn A",priority:"Cao",due:"2026-10-05",status:"Đang làm",progress:70},{id:2,title:"Kiểm tra hồ sơ ứng viên",dept:"Cung ứng lao động",assignee:"Trần Thị B",priority:"Cao",due:"2026-10-07",status:"Đang làm",progress:40},{id:3,title:"Chuẩn bị khai giảng lớp HSK1",dept:"Giáo dục",assignee:"Lê Thị C",priority:"Trung bình",due:"2026-10-03",status:"Hoàn thành",progress:100},{id:4,title:"Liên hệ đối tác tuyển sinh",dept:"Giáo dục",assignee:"Phạm Văn D",priority:"Thấp",due:"2026-10-12",status:"Chưa làm",progress:0}],employees:[{id:1,name:"Nguyễn Văn A",role:"Nhân viên",dept:"Cung ứng lao động"},{id:2,name:"Trần Thị B",role:"Nhân viên",dept:"Cung ứng lao động"},{id:3,name:"Lê Thị C",role:"Giáo viên/Điều phối",dept:"Giáo dục"},{id:4,name:"Phạm Văn D",role:"Kinh doanh",dept:"Giáo dục"}]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed,page="dashboard",user=null,profile=null,cloud=!!sb;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const badge=t=>{let c=t==="Hoàn thành"?"done":t==="Đang làm"?"doing":"todo";return `<span class="badge ${c}">${esc(t)}</span>`};

async function boot(){
 if(!sb){shell();return}
 const {data:{session}}=await sb.auth.getSession();
 if(session){user=session.user;await loadCloud();shell()}else login();
 sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user){await loadCloud();shell()}else login()});
}
function login(msg="",email=""){
 document.getElementById("app").innerHTML=`<div class="auth"><div class="authbox"><h1>LIÊN HOA</h1><p>WORK MANAGER</p><div class="authmode"><button id="loginTab" class="btn primary" onclick="authMode('login')">Đăng nhập</button><button id="signupTab" class="btn" onclick="authMode('signup')">Tạo tài khoản</button></div><form onsubmit="authSubmit(event)"><label class="field">Email<input id="email" type="email" value="${esc(email)}" required></label><label class="field">Mật khẩu<input id="password" type="password" minlength="6" required></label><label class="field" id="nameField" style="display:none">Họ và tên<input id="fullname"></label><p id="authMsg" class="label">${esc(msg)}</p><button class="btn primary fullbtn" id="authBtn">Đăng nhập</button></form><div class="authlinks"><button class="linkbtn" type="button" onclick="forgotPassword()">Quên mật khẩu?</button><button class="linkbtn" type="button" onclick="resendConfirmation()">Gửi lại email xác nhận</button></div></div></div>`;
 window.authMode=authMode; window.authSubmit=authSubmit; window.forgotPassword=forgotPassword; window.resendConfirmation=resendConfirmation;
}
let mode="login";
function authMode(m){mode=m;document.getElementById("nameField").style.display=m==="signup"?"block":"none";document.getElementById("authBtn").textContent=m==="signup"?"Tạo tài khoản":"Đăng nhập";document.getElementById("loginTab").className="btn "+(m==="login"?"primary":"");document.getElementById("signupTab").className="btn "+(m==="signup"?"primary":"")}
function authError(err){let s=(err?.message||"").toLowerCase();if(s.includes("invalid login credentials"))return "Email hoặc mật khẩu không đúng, hoặc tài khoản chưa xác nhận email.";if(s.includes("email not confirmed"))return "Email chưa được xác nhận. Hãy kiểm tra hộp thư và bấm liên kết xác nhận.";if(s.includes("user already registered"))return "Email này đã có tài khoản. Hãy đăng nhập hoặc dùng Quên mật khẩu.";return err?.message||"Có lỗi xảy ra. Vui lòng thử lại."}
async function authSubmit(e){
 e.preventDefault();
 let email=emailEl().value.trim(),password=passwordEl().value,fullname=document.getElementById("fullname")?.value.trim();
 if(!sb){login("Hệ thống đăng nhập Cloud chưa được cấu hình.");return}
 if(mode==="signup"){
   let r=await sb.auth.signUp({email,password,options:{data:{full_name:fullname||email}}});
   if(r.error){login(authError(r.error),email);return}
   if(r.data?.session){user=r.data.user;await loadCloud();shell();return}
   login("Tài khoản đã tạo thành công. Hãy kiểm tra email để xác nhận tài khoản rồi đăng nhập.",email);
 }else{
   let r=await sb.auth.signInWithPassword({email,password});
   if(r.error){login(authError(r.error),email);return}
   user=r.data.user;await loadCloud();shell();
 }
}
async function resendConfirmation(){
 let email=emailEl()?.value.trim();if(!email){login("Nhập email trước rồi bấm gửi lại email xác nhận.");return}
 let r=await sb.auth.resend({type:"signup",email});if(r.error)login(authError(r.error),email);else login("Đã gửi lại email xác nhận. Hãy kiểm tra Inbox và cả Spam.",email);
}
async function forgotPassword(){
 let email=emailEl()?.value.trim();if(!email){login("Nhập email rồi bấm Quên mật khẩu.");return}
 let redirectTo=location.origin+location.pathname;
 let r=await sb.auth.resetPasswordForEmail(email,{redirectTo});if(r.error)login(authError(r.error),email);else login("Đã gửi email đặt lại mật khẩu. Hãy kiểm tra Inbox và Spam.",email);
}
const emailEl=()=>document.getElementById("email"),passwordEl=()=>document.getElementById("password");

async function loadCloud(){
 const [p,t,e]=await Promise.all([sb.from("profiles").select("*").eq("id",user.id).maybeSingle(),sb.from("tasks").select("*,assignee:profiles!tasks_assignee_id_fkey(full_name)").order("due_date"),sb.from("profiles").select("*").order("full_name")]);
 if(!p.error&&p.data)profile=p.data;
 if(!t.error)db.tasks=(t.data||[]).map(x=>({id:x.id,title:x.title,dept:x.department,assignee:x.assignee?.full_name||"Chưa giao",assignee_id:x.assignee_id,priority:x.priority,due:x.due_date||"",status:x.status,progress:x.progress}));
 if(!e.error)db.employees=(e.data||[]).map(x=>({id:x.id,name:x.full_name,role:x.role,dept:x.department||""}));
 cloud=true;
}
function shell(){document.getElementById("app").innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">LIÊN HOA WORK MANAGER<small>Education & Labor Supply</small></div><nav class="nav"><button class="${page==="dashboard"?"active":""}" onclick="go('dashboard')">📊 Dashboard</button><button class="${page==="tasks"?"active":""}" onclick="go('tasks')">✅ Công việc</button><button class="${page==="employees"?"active":""}" onclick="go('employees')">👥 Nhân sự</button><button class="${page==="education"?"active":""}" onclick="go('education')">🎓 Giáo dục</button><button class="${page==="labor"?"active":""}" onclick="go('labor')">💼 Cung ứng lao động</button><button class="${page==="study"?"active":""}" onclick="go('study')">🌏 Du học</button><button class="${page==="recruit"?"active":""}" onclick="go('recruit')">🧑‍🏫 Tuyển sinh trung tâm</button><button class="${page==="exportLabor"?"active":""}" onclick="go('exportLabor')">✈️ Xuất khẩu lao động</button><button class="${page==="calendar"?"active":""}" onclick="go('calendar')">📅 Lịch công việc</button></nav><button class="logout" onclick="logout()">Đăng xuất</button></aside><main class="main"><div class="top"><h1>${({dashboard:"Dashboard",tasks:"Quản lý công việc",employees:"Nhân sự",education:"Giáo dục",labor:"Cung ứng lao động",calendar:"Lịch công việc",study:"Du học",recruit:"Tuyển sinh trung tâm",exportLabor:"Xuất khẩu lao động"})[page]}</h1><div class="user">👤 ${esc(profile?.full_name||user?.email||"Giám đốc")} <small>${esc(profile?.role||"")}</small></div></div><div id="content"></div></main></div>`;render()}
function go(p){page=p;shell()}
function render(){let c=document.getElementById("content");if(page==="dashboard")dashboard(c);else if(page==="tasks")tasks(c);else if(page==="employees")employees(c);else if(page==="education")filtered(c,"Giáo dục","Công việc Giáo dục");else if(page==="labor")filtered(c,"Cung ứng lao động","Công việc Cung ứng lao động");else if(page==="study")filtered(c,"Du học","Quản lý Du học");else if(page==="recruit")filtered(c,"Tuyển sinh trung tâm","Tuyển sinh Trung tâm");else if(page==="exportLabor")filtered(c,"Xuất khẩu lao động","Quản lý Xuất khẩu lao động");else calendar(c)}
function dashboard(c){let t=db.tasks,done=t.filter(x=>x.status==="Hoàn thành").length,doing=t.filter(x=>x.status==="Đang làm").length,late=t.filter(x=>x.status!=="Hoàn thành"&&x.due&&x.due<new Date().toISOString().slice(0,10)).length;c.innerHTML=`<div class="cards"><div class="card"><div class="label">Tổng công việc</div><div class="value">${t.length}</div></div><div class="card"><div class="label">Đang thực hiện</div><div class="value">${doing}</div></div><div class="card"><div class="label">Hoàn thành</div><div class="value">${done}</div></div><div class="card"><div class="label">Quá hạn</div><div class="value">${late}</div></div></div><div class="grid"><section class="panel"><h2>Công việc gần nhất</h2>${taskTable(t.slice().sort((a,b)=>a.due.localeCompare(b.due)).slice(0,6))}</section><section class="panel"><h2>Khối lượng theo nhân viên</h2>${db.employees.map(e=>{let n=t.filter(x=>x.assignee===e.name).length;return `<p><b>${esc(e.name)}</b><span style="float:right">${n} việc</span></p><div class="progress"><i style="width:${Math.min(100,n*25)}%"></i></div>`}).join("")}</section></div>`}
function taskTable(arr){return `<table><thead><tr><th>Công việc</th><th>Người phụ trách</th><th>Deadline</th><th>Tiến độ</th><th>Trạng thái</th><th></th></tr></thead><tbody>${arr.map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="label">${esc(x.dept)} · ${esc(x.priority)}</span></td><td>${esc(x.assignee)}</td><td>${esc(x.due)}</td><td><div class="progress"><i style="width:${x.progress}%"></i></div><small>${x.progress}%</small></td><td>${badge(x.status)}</td><td><button class="btn" onclick="openTask('${x.id}')">Sửa</button></td></tr>`).join("")}</tbody></table>`}
function tasks(c){c.innerHTML=`<div class="toolbar"><input id="q" class="search" placeholder="Tìm công việc..." oninput="filterTasks()"><button class="btn primary" onclick="openTask()">+ Giao công việc</button><button class="btn" onclick="exportTasks()">⬇ Xuất CSV</button></div><section class="panel"><div id="tasklist">${taskTable(db.tasks)}</div></section>`}
function filterTasks(){let q=document.getElementById("q").value.toLowerCase();document.getElementById("tasklist").innerHTML=taskTable(db.tasks.filter(x=>(x.title+x.assignee+x.dept).toLowerCase().includes(q)))}
function employees(c){c.innerHTML=`<div class="toolbar"><button class="btn primary" onclick="openEmployee()">+ Thêm nhân viên</button></div><section class="panel"><table><thead><tr><th>Họ tên</th><th>Chức vụ</th><th>Phòng ban</th><th>Công việc</th></tr></thead><tbody>${db.employees.map(e=>`<tr><td><b>${esc(e.name)}</b></td><td>${esc(e.role)}</td><td>${esc(e.dept)}</td><td>${db.tasks.filter(x=>x.assignee===e.name).length}</td></tr>`).join("")}</tbody></table></section>`}
function filtered(c,dept,title){c.innerHTML=`<section class="panel"><h2>${title}</h2>${taskTable(db.tasks.filter(x=>x.dept===dept))}</section>`}
function calendar(c){c.innerHTML=`<section class="panel"><h2>Lịch công việc theo deadline</h2>${taskTable(db.tasks.slice().sort((a,b)=>a.due.localeCompare(b.due)))}</section>`}
function openTask(id=null){let x=id?db.tasks.find(t=>String(t.id)===String(id)):null;document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><h2>${x?"Cập nhật công việc":"Giao công việc mới"}</h2><form onsubmit="addTask(event)"><input type="hidden" name="id" value="${x?.id||""}"><div class="formgrid"><label class="field full">Tên công việc<input name="title" value="${esc(x?.title||"")}" required></label><label class="field">Phòng ban<select name="dept"><option ${x?.dept==="Giáo dục"?"selected":""}>Giáo dục</option><option ${x?.dept==="Cung ứng lao động"?"selected":""}>Cung ứng lao động</option><option>Hành chính</option><option>Kinh doanh</option><option>Du học</option><option>Tuyển sinh trung tâm</option><option>Xuất khẩu lao động</option></select></label><label class="field">Người phụ trách<select name="assignee_id"><option value="">Chưa giao</option>${db.employees.map(e=>`<option value="${esc(e.id)}" ${x?.assignee_id===e.id?"selected":""}>${esc(e.name)}</option>`).join("")}</select></label><label class="field">Deadline<input name="due" type="date" value="${esc(x?.due||"")}" required></label><label class="field">Ưu tiên<select name="priority"><option ${x?.priority==="Cao"?"selected":""}>Cao</option><option ${x?.priority==="Trung bình"?"selected":""}>Trung bình</option><option ${x?.priority==="Thấp"?"selected":""}>Thấp</option></select></label><label class="field">Trạng thái<select name="status"><option ${x?.status==="Chưa làm"?"selected":""}>Chưa làm</option><option ${x?.status==="Đang làm"?"selected":""}>Đang làm</option><option ${x?.status==="Hoàn thành"?"selected":""}>Hoàn thành</option></select></label><label class="field">Tiến độ (%)<input name="progress" type="number" min="0" max="100" value="${x?.progress||0}"></label></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Hủy</button><button class="btn primary">${x?"Lưu thay đổi":"Giao việc"}</button></div></form></div></div>`)}
async function addTask(e){e.preventDefault();let f=new FormData(e.target),id=f.get("id"),aid=f.get("assignee_id")||null,base={title:f.get("title"),department:f.get("dept"),assignee_id:aid,priority:f.get("priority"),due_date:f.get("due"),status:f.get("status"),progress:Number(f.get("progress")||0)};if(cloud){let r=id?await sb.from("tasks").update(base).eq("id",id):await sb.from("tasks").insert({...base,creator_id:user.id});if(r.error){alert(r.error.message);return}await loadCloud()}else{let emp=db.employees.find(e=>String(e.id)===String(aid));let data={id:id||Date.now(),title:base.title,dept:base.department,assignee:emp?.name||"Chưa giao",assignee_id:aid,priority:base.priority,due:base.due_date,status:base.status,progress:base.progress};if(id)db.tasks=db.tasks.map(t=>String(t.id)===String(id)?data:t);else db.tasks.push(data);save()}closeModal();render()}
function openEmployee(){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><h2>Thêm nhân viên</h2><form onsubmit="addEmployee(event)"><div class="formgrid"><label class="field full">Họ tên<input name="name" required></label><label class="field">Chức vụ<input name="role" value="Nhân viên"></label><label class="field">Phòng ban<select name="dept"><option>Giáo dục</option><option>Cung ứng lao động</option><option>Du học</option><option>Tuyển sinh trung tâm</option><option>Xuất khẩu lao động</option><option>Hành chính</option><option>Kinh doanh</option></select></label></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Hủy</button><button class="btn primary">Lưu</button></div></form></div></div>`)}
async function addEmployee(e){e.preventDefault();let f=new FormData(e.target);if(cloud){alert("Nhân sự Cloud cần tạo tài khoản Supabase trước. Hãy dùng nút Tạo tài khoản ở màn hình đăng nhập; sau khi đăng ký, tài khoản sẽ tự xuất hiện trong Nhân sự.");closeModal();return}db.employees.push({id:Date.now(),name:f.get("name"),role:f.get("role"),dept:f.get("dept")});save();closeModal();render()}
function exportTasks(){let rows=[["Công việc","Phòng ban","Phụ trách","Ưu tiên","Deadline","Trạng thái","Tiến độ"],...db.tasks.map(x=>[x.title,x.dept,x.assignee,x.priority,x.due,x.status,x.progress])];let csv="\\ufeff"+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(",")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="lien-hoa-cong-viec.csv";a.click()}
function closeModal(){document.getElementById("modal")?.remove()}
async function logout(){if(sb)await sb.auth.signOut()}
boot();